### ISSUE TITLE
Update hdash to look for new manifest naming pattern

### ISSUE THREAD

**Issue by adamjtaylor** [ncihtan/hdash#7]
As part of the transfer from storing clinical and biospecimen entries as entities to rows in tables, all manifests have been transfered from the previous `synapse_storage_manifest.csv` files to new files with the pattern `synapse_storage_manifest_[component].csv`,

For example `synapse_storage_manifest_biospecimen.csv` or `synapse_storage_manifest_imaginglevel2.csv`

The HTAN dashboard needs to be updated to look for these, possibly through a regex, as currently I think it looks only for `synapse_storage_manifest.csv`

https://github.com/ncihtan/hdash/blob/9dc6bb2359811d16bc18394d020c29d8e80064d2/hdash/synapse/htan_project.py#L61

This is a critical issue as all metadata is now stored in these new files and new metadata will be submitted into them.

**Comment by adamjtaylor** [comment]
@ecerami I think we have everything now moved over.... Could you now deploy the update to look at the new manifests - at least for a first test!
FYI @GiaJordan @aclayton555

**Comment by ecerami** [comment]
sure, adding to my list.  will ping back once I have new info.

**Comment by ecerami** [comment]
@adamjtaylor code fix now deployed at http://htan_dashboard.surge.sh/.  Seems ok, but you may want to poke around to make sure.

**Comment by GiaJordan** [comment]
@ecerami @adamjtaylor Please note: TNP - TMA is not showing metadata on the dashboard, but is likely due to the fact that this project has not been migrated because of the fileview issue we discussed before on slack. I'm still aware and can migrate this project once we decide how to handle the view
**cc** @milen-sage

**Comment by adamjtaylor** [comment]
Thanks Ethan. Looks ok for now. TMA has been migrated as well so should now show up.
Closing this issue
