### ISSUE TITLE
HTAN Dashboard 10x Visium Update

### ISSUE THREAD

**Issue by PozhidayevaDarya** [ncihtan/hdash#8]
Since we've recently launched the Visium template in the DCA and begun to receive data from centers, it would follow that the dashboard should be updated to display this new data type. Would this be possible?

Visium should be associated with the following component names:
“10x Visium Spatial Transcriptomics - RNA-seq Level 1”
“10x Visium Spatial Transcriptomics - RNA-seq Level 2"
“10x Visium Spatial Transcriptomics - Auxiliary Files Level 2”
“10x Visium Spatial Transcriptomics - RNA-seq Level 3"

**Comment by ecerami** [comment]
Yes, I can add to my list.

**Comment by ecerami** [comment]
@PozhidayevaDarya just confirming here, are there two kinds of Visium Level 2 files?

**Comment by PozhidayevaDarya** [comment]
> @PozhidayevaDarya just confirming here, are there two kinds of Visium Level 2 files?

@ecerami are you referring to the two different visium level 2 folders (visium level 2 and visium level 2 ccrcc23)?
If so, this is two distinct studies/sets rather than being different kinds of files per-se. Does that make sense?

**Comment by ecerami** [comment]
@PozhidayevaDarya sorry, no I was referring to the list up top, e.g.

“10x Visium Spatial Transcriptomics - RNA-seq Level 1”
“10x Visium Spatial Transcriptomics - RNA-seq Level 2"
“10x Visium Spatial Transcriptomics - Auxiliary Files Level 2”
“10x Visium Spatial Transcriptomics - RNA-seq Level 3"

This seems to indicates that the data curator supports two kinds of level 2 meta data templates?

**Comment by PozhidayevaDarya** [comment]
@ecerami Ah okay, yes that is correct there are two level 2s!
One is sequencing specific and the other accommodates other related data (images) passed as arguments to space ranger.
Thanks for checking!

**Comment by ecerami** [comment]
ok, thanks.  This is now fixed then.  I added Visium to the dashboard along with Visium completeness heatmap.  Will be part of release later this week.
