### ISSUE TITLE
Clinical/biospecimen no longer stored as entities on Synapse

### ISSUE THREAD

**Issue by clarisse-lau** [ncihtan/hdash#9]
The Sage team recently moved away from storing clinical and biospecimen records as Synapse entities. Rather the manifest is now stored as a Synapse table. 

The result of this is that any records submitted after this change was made will no longer have a Synapse entityId (they are given Uuids as unique identifiers instead). 

We may want to update hdash to reflect that this isn't an error. For example, there are some currently listed for WUSTL: 
http://htan_dashboard.surge.sh/HTA12.html

**Comment by ecerami** [comment]
@clarisse-lau thanks.  What's the error on the dashboard now that I should mask?

**Comment by clarisse-lau** [comment]
For example: 
- Therapy has invalid Synapse ID: nan.
- Demographics has invalid Synapse ID: nan.

Plus all of the other clinical elements (e.g. Diagnosis, Exposure, etc.) may have nulls as Synapse ID, and that is expected going forward

**Comment by ecerami** [comment]
@clarisse-lau OK, do you think these are all part of the H_ENTITY_ID check?  or is it more complicated than that?

**Comment by ecerami** [comment]
This is now fixed, but not yet deployed.  Will be part of deployment later this week.
